  ---
functional:
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна поссылке)
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегестрированные пользователи
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык програмирования во время решения 
  - Решение задачи на скорость против другого игрока
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась. Кнопка "check" у него более неактивна, но он может остаться и посмотреть ещё раз на свой код
  - Соперник тоже может выйти, а может доиграть до конца
  - Оба видят два редактора: слева - свой редактор, справа - соперника
  - Каждый игрок видит код своего соперника в режиме он-лайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки неограниченно
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  - Пользователь находится в режиме ожидания второго игрока
  - Игра высвечивается как "доступная для подключения" у других пользователей
  - Второй пользователь нажимает "connect to game"
  - Обоих перебрасывает в игру
  - Пользователь авторизуется
  - Пользователь просто нажимает "Create game" (выбор языка позже)
non-functional:
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках русском и английском
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрователь
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое кол-во трафика (например, 1000 одновременнях пользователей)
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
  - Наверху находится время игры и ниже - задание (позже будет ещё чат слева) 
  - Игра пока может длиться неограниченное время
implicit:
  - сайт должен быть безопасным 
  - личные данные пользователей должны быть защищены
  - Пользователь должен иметь возможность менять язык сайта на главной странице или в настройках
  - Пользователю должно быть предложено обучение по сайту
  
