  ---
functional:
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна поссылке)
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегестрированные пользователи
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык програмирования во время решения 
  - Решение задачи на скорость против другого игрока
non-functional:
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках русском и английском
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрователь
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое кол-во трафика (например, 1000 одновременнях пользователей)
implicit:
  - В русской версии сайта названия категорий должны быть переведены на русский язык
  - У пользователя должна быть возможность подтвердить оформление заказа
  - В русской версии сайта цены должны быть переведены в рубли
  - У пользователей должна быть возможность оплатить заказ
  - для вступления в игру пользователь должен быть зарегистрирован и авторизован
  - пользователь не может редактировать чужой код
  - сайт должен быть безопасным 
  - личные данные пользователей должны быть защищены
  - сайт должен соответствовать всем применимым законам и правилам
  - сайт должен быть доступным, когда это необходимо
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность переключать/менять язык сайта на стартовой странице или в личных настройках.
  - Пользователю должно быть предложено обучение по пользованию сайта.
  
